
export const includedBlocks = new Set([
	"basic-latin",
	"latin-1-supplement",
	"latin-extended-a",
	"latin-extended-b",
	"ipa-extensions",
	"spacing-modifier-letters",
	"combining-diacritical-marks",
	"greek-and-coptic",
	"cyrillic",
	"cyrillic-supplement",
	"hebrew",
	"combining-diacritical-marks-extended",
	"cyrillic-extended-c",
	"phonetic-extensions",
	"phonetic-extensions-supplement",
	"combining-diacritical-marks-supplement",
	"latin-extended-additional",
	"greek-extended",
	"general-punctuation",
	"superscripts-and-subscripts",
	"currency-symbols",
	"combining-diacritical-marks-for-symbols",
	"letterlike-symbols",
	"number-forms",
	"arrows",
	"mathematical-operators",
	"miscellaneous-technical",
	"control-pictures",
	"optical-character-recognition",
	"enclosed-alphanumerics",
	"box-drawing",
	"block-elements",
	"geometric-shapes",
	"miscellaneous-symbols",
	"dingbats",
	"miscellaneous-mathematical-symbols-a",
	"supplemental-arrows-a",
	"braille-patterns",
	"supplemental-arrows-b",
	"miscellaneous-mathematical-symbols-b",
	"supplemental-mathematical-operators",
	"miscellaneous-symbols-and-arrows",
	"latin-extended-c",
	"cyrillic-extended-a",
	"supplemental-punctuation",
	"ideographic-description-characters",
	"cjk-symbols-and-punctuation",
	"enclosed-cjk-letters-and-months",
	"cjk-compatibility",
	"yijing-hexagram-symbols",
	"cyrillic-extended-b",
	"modifier-tone-letters",
	"latin-extended-d",
	"latin-extended-e",
	"variation-selectors",
	"vertical-forms",
	"combining-half-marks",
	"cjk-compatibility-forms",
	"small-form-variants",
	// "arabic-presentation-forms-b",
	"halfwidth-and-fullwidth-forms",
	"specials",
	"latin-extended-f",
	"shorthand-format-controls",
	"musical-symbols",
	"tai-xuan-jing-symbols",
	// "counting-rod-numerals",
	"mathematical-alphanumeric-symbols",
	"latin-extended-g",
	"cyrillic-extended-d",
	"mahjong-tiles",
	"domino-tiles",
	"playing-cards",
	"enclosed-alphanumeric-supplement",
	"enclosed-ideographic-supplement",
	"miscellaneous-symbols-and-pictographs",
	"emoticons",
	"ornamental-dingbats",
	"transport-and-map-symbols",
	"geometric-shapes-extended",
	"supplemental-arrows-c",
	"supplemental-symbols-and-pictographs",
	"chess-symbols",
	"symbols-and-pictographs-extended-a",
]);

export const controlCharacterMappings = new Map([
	[0x00, "\u2400"],
	[0x01, "\u2401"],
	[0x02, "\u2402"],
	[0x03, "\u2403"],
	[0x04, "\u2404"],
	[0x05, "\u2405"],
	[0x06, "\u2406"],
	[0x07, "\u2407"],
	[0x08, "\u2408"],
	[0x09, "\u2409"],
	[0x0A, "\u240A"],
	[0x0B, "\u240B"],
	[0x0C, "\u240C"],
	[0x0D, "\u240D"],
	[0x0E, "\u240E"],
	[0x0F, "\u240F"],
	[0x10, "\u2410"],
	[0x11, "\u2411"],
	[0x12, "\u2412"],
	[0x13, "\u2413"],
	[0x14, "\u2414"],
	[0x15, "\u2415"],
	[0x16, "\u2416"],
	[0x17, "\u2417"],
	[0x18, "\u2418"],
	[0x19, "\u2419"],
	[0x1A, "\u241A"],
	[0x1B, "\u241B"],
	[0x1C, "\u241C"],
	[0x1D, "\u241D"],
	[0x1E, "\u241E"],
	[0x1F, "\u241F"],
	[0x7F, "\u2421"],
	[0x80, "\uFFFD"],
	[0x81, "\uFFFD"],
	[0x82, "\uFFFD"],
	[0x83, "\uFFFD"],
	[0x84, "\uFFFD"],
	[0x85, "\uFFFD"],
	[0x86, "\uFFFD"],
	[0x87, "\uFFFD"],
	[0x88, "\uFFFD"],
	[0x89, "\uFFFD"],
	[0x8A, "\uFFFD"],
	[0x8B, "\uFFFD"],
	[0x8C, "\uFFFD"],
	[0x8D, "\uFFFD"],
	[0x8E, "\uFFFD"],
	[0x8F, "\uFFFD"],
	[0x90, "\uFFFD"],
	[0x91, "\uFFFD"],
	[0x92, "\uFFFD"],
	[0x93, "\uFFFD"],
	[0x94, "\uFFFD"],
	[0x95, "\uFFFD"],
	[0x96, "\uFFFD"],
	[0x97, "\uFFFD"],
	[0x98, "\uFFFD"],
	[0x99, "\uFFFD"],
	[0x9A, "\uFFFD"],
	[0x9B, "\uFFFD"],
	[0x9C, "\uFFFD"],
	[0x9D, "\uFFFD"],
	[0x9E, "\uFFFD"],
	[0x9F, "\uFFFD"],
]);

export const shrinkedCharacters = new Set<number>([
	0x20E0,
	0x20E2,
	0x20E4,
	0x213B,
	0x27F5,
	0x27F6,
	0x27F7,
	0x27F8,
	0x27F9,
	0x27FA,
	0x27FB,
	0x27FC,
	0x27FD,
	0x27FE,
	0x27FF,
	0x2E3A,
	0x2E3B,
	0x1F67C,
	0x1F67D,
	0x1F67E,
	0x1F67F,
]);

export const nonPrintableCharacters = [
	["0000", "NULL"],
	["0001", "START OF HEADING"],
	["0002", "START OF TEXT"],
	["0003", "END OF TEXT"],
	["0004", "END OF TRANSMISSION"],
	["0005", "ENQUIRY"],
	["0006", "ACKNOWLEDGE"],
	["0007", "BELL"],
	["0008", "BACKSPACE"],
	["0009", "CHARACTER TABULATION"],
	["000A", "LINE FEED (LF)"],
	["000B", "LINE TABULATION"],
	["000C", "FORM FEED (FF)"],
	["000D", "CARRIAGE RETURN (CR)"],
	["000E", "SHIFT OUT"],
	["000F", "SHIFT IN"],
	["0010", "DATA LINK ESCAPE"],
	["0011", "DEVICE CONTROL ONE"],
	["0012", "DEVICE CONTROL TWO"],
	["0013", "DEVICE CONTROL THREE"],
	["0014", "DEVICE CONTROL FOUR"],
	["0015", "NEGATIVE ACKNOWLEDGE"],
	["0016", "SYNCHRONOUS IDLE"],
	["0017", "END OF TRANSMISSION BLOCK"],
	["0018", "CANCEL"],
	["0019", "END OF MEDIUM"],
	["001A", "SUBSTITUTE"],
	["001B", "ESCAPE"],
	["001C", "INFORMATION SEPARATOR FOUR (FILE)"],
	["001D", "INFORMATION SEPARATOR THREE (GROUP)"],
	["001E", "INFORMATION SEPARATOR TWO (RECORD)"],
	["001F", "INFORMATION SEPARATOR ONE (UNIT)"],
	["0020", "SPACE"],
	["007F", "DELETE"],
	["0080", "(PADDING CHARACTER)"],
	["0081", "(HIGH OCTET PRESET)"],
	["0082", "BREAK PERMITTED HERE"],
	["0083", "NO BREAK HERE"],
	["0084", "(INDEX)"],
	["0085", "NEXT LINE (NEL)"],
	["0086", "START OF SELECTED AREA"],
	["0087", "END OF SELECTED AREA"],
	["0088", "CHARACTER TABULATION SET"],
	["0089", "CHARACTER TABULATION WITH JUSTIFICATION"],
	["008A", "LINE TABULATION SET"],
	["008B", "PARTIAL LINE FORWARD"],
	["008C", "PARTIAL LINE BACKWARD"],
	["008D", "REVERSE LINE FEED"],
	["008E", "SINGLE SHIFT TWO"],
	["008F", "SINGLE SHIFT THREE"],
	["0090", "DEVICE CONTROL STRING"],
	["0091", "PRIVATE USE ONE"],
	["0092", "PRIVATE USE TWO"],
	["0093", "SET TRANSMIT STATE"],
	["0094", "CANCEL CHARACTER"],
	["0095", "MESSAGE WAITING"],
	["0096", "START OF GUARDED AREA"],
	["0097", "END OF GUARDED AREA"],
	["0098", "START OF STRING"],
	["0099", "(SINGLE GRAPHIC CHARACTER INTRODUCER)"],
	["009A", "SINGLE CHARACTER INTRODUCER"],
	["009B", "CONTROL SEQUENCE INTRODUCER"],
	["009C", "STRING TERMINATOR"],
	["009D", "OPERATING SYSTEM COMMAND"],
	["009E", "PRIVACY MESSAGE"],
	["009F", "APPLICATION PROGRAM COMMAND"],
	["00A0", "NO-BREAK SPACE"],
	["00AD", "SOFT HYPHEN"],
	["034F", "COMBINING GRAPHEME JOINER"],
	["061C", "ARABIC LETTER MARK"],
	["061D", "ARABIC END OF TEXT MARK"],
	["115F", "HANGUL CHOSEONG FILLER"],
	["1160", "HANGUL JUNGSEONG FILLER"],
	["1680", "OGHAM SPACE MARK"],
	["17B4", "KHMER VOWEL INHERENT AQ"],
	["17B5", "KHMER VOWEL INHERENT AA"],
	["180B", "MONGOLIAN FREE VARIATION SELECTOR ONE"],
	["180C", "MONGOLIAN FREE VARIATION SELECTOR TWO"],
	["180D", "MONGOLIAN FREE VARIATION SELECTOR THREE"],
	["180E", "MONGOLIAN VOWEL SEPARATOR"],
	["2000", "EN QUAD"],
	["2001", "EM QUAD"],
	["2002", "EN SPACE"],
	["2003", "EM SPACE"],
	["2004", "THREE-PER-EM SPACE"],
	["2005", "FOUR-PER-EM SPACE"],
	["2006", "SIX-PER-EM SPACE"],
	["2007", "FIGURE SPACE"],
	["2008", "PUNCTUATION SPACE"],
	["2009", "THIN SPACE"],
	["200A", "HAIR SPACE"],
	["200B", "ZERO WIDTH SPACE"],
	["200C", "ZERO WIDTH NON-JOINER"],
	["200D", "ZERO WIDTH JOINER"],
	["200E", "LEFT-TO-RIGHT MARK"],
	["200F", "RIGHT-TO-LEFT MARK"],
	["2028", "LINE SEPARATOR"],
	["2029", "PARAGRAPH SEPARATOR"],
	["202A", "LEFT-TO-RIGHT EMBEDDING"],
	["202B", "RIGHT-TO-LEFT EMBEDDING"],
	["202C", "POP DIRECTIONAL FORMATTING"],
	["202D", "LEFT-TO-RIGHT OVERRIDE"],
	["202E", "RIGHT-TO-LEFT OVERRIDE"],
	["202F", "NARROW NO-BREAK SPACE"],
	["205F", "MEDIUM MATHEMATICAL SPACE"],
	["2060", "WORD JOINER"],
	["2061", "FUNCTION APPLICATION"],
	["2062", "INVISIBLE TIMES"],
	["2063", "INVISIBLE SEPARATOR"],
	["2064", "INVISIBLE PLUS"],
	["2066", "LEFT-TO-RIGHT ISOLATE"],
	["2067", "RIGHT-TO-LEFT ISOLATE"],
	["2068", "FIRST STRONG ISOLATE"],
	["2069", "POP DIRECTIONAL ISOLATE"],
	["206A", "INHIBIT SYMMETRIC SWAPPING"],
	["206B", "ACTIVATE SYMMETRIC SWAPPING"],
	["206C", "INHIBIT ARABIC FORM SHAPING"],
	["206D", "ACTIVATE ARABIC FORM SHAPING"],
	["206E", "NATIONAL DIGIT SHAPES"],
	["206F", "NOMINAL DIGIT SHAPES"],
	["2800", "BRAILLE PATTERN BLANK"],
	["3000", "IDEOGRAPHIC SPACE"],
	["3164", "HANGUL FILLER"],
	["FE00..FE0D", "VARIATION SELECTOR-1..14"],
	["FE0E", "VARIATION SELECTOR-15 (TEXT)"],
	["FE0F", "VARIATION SELECTOR-16 (EMOJI)"],
	["FEFF", "ZERO WIDTH NO-BREAK SPACE (BOM)"],
	["FFA0", "HALFWIDTH HANGUL FILLER"],
	["FFF9", "INTERLINEAR ANNOTATION ANCHOR"],
	["FFFA", "INTERLINEAR ANNOTATION SEPARATOR"],
	["FFFB", "INTERLINEAR ANNOTATION TERMINATOR"],
	["FFFC", "OBJECT REPLACEMENT CHARACTER"],
	["1BCA0", "SHORTHAND FORMAT LETTER OVERLAP"],
	["1BCA1", "SHORTHAND FORMAT LETTER CONTINUING OVERLAP"],
	["1BCA2", "SHORTHAND FORMAT LETTER CONTINUING DOWN STEP"],
	["1BCA3", "SHORTHAND FORMAT LETTER CONTINUING UP STEP"],
	["1D159", "MUSICAL SYMBOL NULL NOTEHEAD"],
	["1D173", "MUSICAL SYMBOL BEGIN BEAM"],
	["1D174", "MUSICAL SYMBOL END BEAM"],
	["1D175", "MUSICAL SYMBOL BEGIN TIE"],
	["1D176", "MUSICAL SYMBOL END TIE"],
	["1D177", "MUSICAL SYMBOL BEGIN SLUR"],
	["1D178", "MUSICAL SYMBOL END SLUR"],
	["1D179", "MUSICAL SYMBOL BEGIN PHRASE"],
	["1D17A", "MUSICAL SYMBOL END PHRASE"],
	["1F3FB", "EMOJI MODIFIER FITZPATRICK TYPE-1-2"],
	["1F3FC", "EMOJI MODIFIER FITZPATRICK TYPE-3"],
	["1F3FD", "EMOJI MODIFIER FITZPATRICK TYPE-4"],
	["1F3FE", "EMOJI MODIFIER FITZPATRICK TYPE-5"],
	["1F3FF", "EMOJI MODIFIER FITZPATRICK TYPE-6"],
	["E0001", "LANGUAGE TAG"],
	["E0020..E007E", "TAG SPACE..TILDE"],
	["E007F", "CANCEL TAG"],
	["E0100..E01EF", "VARIATION SELECTOR-17..256"],
];
